### ISSUE TITLE
Hoseinzadeh et al. "Use of Electro Hysterogram (EHG) Signal to Diagnose Preterm Birth"

### ISSUE THREAD

**Issue by GillesVandewiele** [GillesVandewiele/EHG-Oversampling#28]
## Reported result
Support vector machine (SVM) was implemented to classify the features, and it is worth noting that by using 10 most superior features, the accuracy rate, sensitivity, and specificity were obtained as 97.1%, 95%, and 99%, respectively. 

## Features

Like Acharya, but with Yule-Walker AR

## Model

In  this  work,  SVM  classifier  with  RBF  kernel  function  is  used for classification of term and preterm delivery using EHG signal records.

## Oversampling

Using  the  ADASYN  method,  we  resample the obtained features and increase the assume data by 514 data

## Comments

!!!!!
Is this plagiarism from the Acharya et al. study???

**Comment by gykovacs** [comment]
very similar, only the features extracted from EMD-WPD are different.
